export declare const CLI_VERSION: any;
export declare const BASE_DIR: string;
export declare const USER_CONFIG_DIR: string;
export declare const LIN_UI_DIR: any;
export declare const NODE_MODULES_DIR_NAME = "node_modules";
export declare const MINI_PROGRAM_DIR_NAME: any;
export declare const NODE_MODULES_LIN_UI_DIR: string;
export declare const MINI_PROGRAM_LIN_UI_DIR: string;
export declare const CORE_DIRS: Set<string>;
export declare const CNPM_BASE_URL = "https://registry.npm.taobao.org/lin-ui";
