export declare const CLI_VERSION: any;
export declare const CLI_NAME: any;
export declare const BASE_DIR: string;
export declare const USER_CONFIG_FILE_NAME = "lin-ui.config.json";
export declare const USER_CONFIG_FILE: string;
export declare const LIN_UI_DIR: string;
export declare const NODE_MODULES_DIR_NAME = "node_modules";
export declare const MINI_PROGRAM_DIR_NAME: string;
export declare const NODE_MODULES_LIN_UI_DIR: string;
export declare const MINI_PROGRAM_LIN_UI_DIR: string;
export declare const CORE_DIRS: Set<string>;
export declare const CNPM_BASE_URL = "https://registry.npm.taobao.org/lin-ui";
export declare const MINI_VERSION_URL = "https://mp.weixin.qq.com/debug/getpublibpercentage";
